### PR TITLE
This is the best story ever written.

### PR DESCRIPTION
**Pull request by SidneyLovelady**

### CODE REVIEW

**Comment by mtseng15** [comment]
@SidneyLovelady Can you move your haiku into the `/haiku` directory? Make another commit to your master and it will propagate here.

**Comment by SidneyLovelady** [comment]
I can when I get to my laptop. Thanks for the heads up!

**Comment by mtseng15** [comment]
Great! No rush. I'll merge it in once you change that.

**Comment by mtseng15** [comment]
Great! Merging in!

**Pull request merged**
